#!/usr/bin/env bash
# Install the tmux-agent-tracker: launchd (login baseline) + tmux hooks + zsh preexec.
# Live updates are hook/launch-driven — no periodic polling. Run after copying the
# files into ~/.tmux-agents. macOS. Idempotent.
set -euo pipefail
DIR="$HOME/.tmux-agents"
LABEL="com.$(id -un).tmux-agents"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
SNAP="/usr/bin/python3 $DIR/snapshot.py >/dev/null 2>&1"
TMUXCONF="$DIR/tmux-agents.tmux"
# PATH for the launchd job — includes Homebrew so it can find the `tmux` binary
# (launchd's default PATH is just /usr/bin:/bin:... which omits /opt/homebrew/bin).
LAUNCHD_PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

[ -f "$DIR/snapshot.py" ] || { echo "copy the files into $DIR first (see README)"; exit 1; }

# 1. launchd: one snapshot at login (baseline). No interval. -----------------
mkdir -p "$HOME/Library/LaunchAgents"
cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array><string>/usr/bin/python3</string><string>$DIR/snapshot.py</string></array>
  <key>EnvironmentVariables</key><dict><key>PATH</key><string>$LAUNCHD_PATH</string></dict>
  <key>RunAtLoad</key><true/>
  <key>StandardOutPath</key><string>$DIR/snapshot.log</string>
  <key>StandardErrorPath</key><string>$DIR/snapshot.log</string>
</dict>
</plist>
EOF
launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST" 2>/dev/null \
  || launchctl load -w "$PLIST" 2>/dev/null \
  || echo "  (could not auto-load launchd; load $PLIST manually)"
echo "launchd: $LABEL (runs at login; live updates are hook/launch-driven)"

# 2. tmux: snapshot on every structural change + wrap the rename key ----------
cat > "$TMUXCONF" <<EOF
# Auto-generated by tmux-agent-tracker install.sh
set-hook -g session-created        'run-shell -b "$SNAP"'
set-hook -g session-closed         'run-shell -b "$SNAP"'
set-hook -g after-new-window       'run-shell -b "$SNAP"'
set-hook -g window-unlinked        'run-shell -b "$SNAP"'
set-hook -g after-split-window     'run-shell -b "$SNAP"'
set-hook -g after-kill-pane        'run-shell -b "$SNAP"'
set-hook -g client-session-changed 'run-shell -b "$SNAP"'
# tmux fires no rename hook, so wrap the rename key to snapshot after renaming.
# (Adjust the key if you don't use M-s for "rename session".)
bind -n M-s command-prompt -p "rename session:" { rename-session "%%" ;; run-shell -b "$SNAP" }
EOF
tmux source-file "$TMUXCONF" 2>/dev/null \
  && echo "tmux: hooks + rename wrap applied to running server" \
  || echo "tmux: no running server (applies on next tmux start)"
CONF="$HOME/.tmux.conf"; SRC="source-file ~/.tmux-agents/tmux-agents.tmux"
grep -qF "$SRC" "$CONF" 2>/dev/null \
  || { printf '\n# tmux-agents\n%s\n' "$SRC" >> "$CONF"; echo "tmux: added source line to $CONF"; }

# 3. zsh: snapshot when an agent is launched by TYPING (no tmux event) --------
ZSHRC="$HOME/.zshrc"; ZSRC="source ~/.tmux-agents/preexec.zsh"
grep -qF "$ZSRC" "$ZSHRC" 2>/dev/null \
  || { printf '\n# tmux-agents\n%s\n' "$ZSRC" >> "$ZSHRC"; echo "zsh: added preexec source to $ZSHRC (open a NEW pane to activate)"; }

# 4. prime once --------------------------------------------------------------
/usr/bin/python3 "$DIR/snapshot.py"
echo "done. db -> $DIR/state.json   restore -> $DIR/restore.sh   view -> python3 $DIR/view.py"
